name: Py Lambda Build
author: Chris  Dawes
description: Build python code into a zip for AWS Lambda
inputs:
  code_dir:
    description: the dir in which the code lives
    required: true
    default: '.'
  out_dir:
    description: the dir to use to assemble the zip contents
    required: true
    default: 'out'
  out_file:
    description: the file path to use for the resulting zip
    required: true
    default: 'lambda.zip'
  requirements_txt:
    description: the name/path of the requirements.txt file in the code dir
    required: true
    default: 'requirements.txt'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.requirements_txt }}
    - ${{ inputs.code_dir }}
    - ${{ inputs.out_file }}
branding:
  icon: 'layers'
  color: 'yellow'
